import { Footer } from "../../content/Footer/Footer";
import { Header } from "../../content/Header/Header";
import { Container, Content, ContentInfo} from "../Home/Home.styles";

import img from './Mercedes.jpg'

export function Mercedes() {
  return(
    <Container>
      <Header/>
      <Content>
        <ContentInfo>
          <h1>Introdução</h1>
          <p>A Mercedes-Benz é uma marca alemã de veículos de luxo e comerciais. Apesar de ser conhecida pelos veículos modernos e de alta tecnologia, a Mercedes é uma marca antiga, com mais de 100 anos de história.</p>
          <p>O Mercedes-Benz Group tem sua origem em um acordo de interesse mútuo entre a Benz & Cie e a Daimler Motoren Gesellschaft no dia 1 de maio de 1924. Nesse acordo, ambas as empresas continuaram a produzir seus próprios carros e motores a combustão, porém, no ano de 1926 as empresas se fundiram de vez, na formalmente chamada Daimler-Benz AG e entraram em consenso que todas as fábricas utilizam o nome de marca Mercedes.</p>
        </ContentInfo>
        <ContentInfo>
          <h1>Breve História da Benz & CIE</h1>
          <p>Um dos fundadores da Benz & Companie Rheinische Gasmotoren-Fabrik, foi o alemão Karl Friedrich Benz, nascido no dia 25 de novembro de 1844, na cidade de Mühlburg no antigo Grão-Ducado de Baden, atual estado de Baden-Wüttenberg da República Federativa da Alemanha.</p>
          <p>No ano seguinte ao de nascimento de Karl, sua mãe se casou, o que fez com que posteriormente ele recebesse o nome “Benz” que antes ele não possuía, devido ao fato de seus pais não serem casados. Porém, seu nome só foi alterado, de Karl Friedrich Michael Vaillant para Karl Friedrich Benz , aos seus dois anos de idade, quando seu pai morreu de pneumonia, então para homenageá-lo, Karl recebeu o nome “Benz”.</p>
          <p>Apesar de viver às margens da pobreza, a mãe de Karl garantiu ao filho uma boa educação em uma escola local. Karl, em seus nove anos de idade, cursou um liceu de orientação científica e após sua conclusão ele estudou na Escola Politécnica de Karlsruhe, sobre as instruções do professor de mecânica e engenharia mecânica, Ferdinand Redtenbacher.</p>
          <p>Em 1871, Karl, após 5 anos de experiência em outras companhias, fundou junto a August Ritter, uma empresa na área de mecânica. No começo o negócio não prosperou de início, pois Ritter não era um homem confiável, o que prejudicava o negócio, mas no ano seguinte a fundação, Bertha Ringer, futura esposa de Karl, comprou a parte de Ritter, e só então o negócio começou a prosperar. Durante o ano de 1878, Benz buscou criar novas patentes, para impulsionar seus negócios, sendo sua principal patente a do motor de dois tempos, um motor cujo ciclo de poder termina após duas pancadas do pistão, e nesse caso, a base de petróleo. Porém, enquanto desenvolvia o motor, Karl patenteou também outras tecnologias como o sistema de regulação de velocidade, o carburador, a embreagem, a vela de carro, a ignição por faísca com bateria e o radiador de água.</p>
          <p>Em 1882, problemas com altos custos de produção, levaram bancos de Mannheim, cidade onde estava sediada a empresa, a exigirem que a empresa de Karl fosse incorporada, o que aconteceu, sendo se tornado uma sociedade por ações, da qual seu fundador ficou com apenas 5 por cento das ações. Além de sua pequena participação em sua própria empresa, Karl decidiu abandoná-la, pois suas ideias eram desconsideradas pelos outros membros, então ele saiu da companhia em 1883.</p>
          <p>Karl Benz gostou, durante boa parte de sua vida, de andar de bicicleta, e foi em uma loja de reparos de bicicletas que ele conheceu Max Rose e Friedrich Wilhelm Eßlinger, junto aos quais ele fundou a Benz & Companie Rheinische Gasmotoren-Fabrik, conhecida como Benz & Cie. A empresa foi um sucesso, de tal forma que Benz conseguiu desenvolver uma de suas paixões, a “carruagem sem cavalos”, utilizando de suas experiências anteriores com motores e bicicletas, Karl Benz havia patenteado o primeiro carro.</p>
          <p>O primeiro carro de Benz, “Benz Patent-Motorwagen”, era movido a gás, tinha rodas de arame, motor de quatro tempos (criado por ele mesmo), uma bobina de ignição e resfriamento evaporativo ao invés de um radiador, a potência era transmitida ao eixo traseiro por meio de duas correntes de rolos. Apesar de inovador, seu primeiro modelo de carro feito em 1885 era difícil de controlar, levando a uma colisão no meio de uma demonstração pública do veículo. Somente no ano seguinte, Benz obteve êxito em sua missão de fazer esse meio de transporte ser mais estável, aprimorando seu veículo em mais dois modelos, o terceiro, que foi apresentado na Exposição Universal de Paris em 1889.</p>
          <p>O inventor vendeu seus veículos a partir do ano de 1888, tendo como um de seus clientes Emile Roger, um homem que já tinha a licença de produção de alguns motores de Benz e passou a vender os automóveis em Paris. Na época, o único entrave na venda de seus veículos era o fato de que eles não subiam colinas, porém a esposa de Benz após um percurso longo dirigindo em direção a casa de sua mãe, sugeriu ao marido que adicionasse mais uma engrenagem ao veículo, que só possuía duas, além disso, ela desenvolveu o conceito de lona de freio e sua viagem foi um marco na história, além de uma boa propaganda para gerar maior confiança por parte do público em automóveis.</p>
          <p>A Benz & Cie, devido a alta demanda de motores de combustão no final do século XIX, se tornou a maior empresa de automóveis do período, o que acarretou no fato dela se tornar uma sociedade por ações. A mudança levou a mudanças na diretoria da empresa, uma delas foi a inclusão de Friedrich von Fischer e Julius Ganß. As mudanças levaram Benz a criar um modelo mais barato de automóvel para produção em massa, sendo o maior destaque o Velocípede e também o Victoria, em menor escala. No ano 1896, Benz patenteou o design do primeiro motor plano, no qual os pistões ficam opostos na posição horizontal e alcançam o ponto morto superior simultaneamente, equilibrando-se entre si com relação ao momento linear.</p>
          <p>A empresa, com o passar dos anos, começou a ter uma competição forte com a Daimler Motoren Gesellschaft, levando os diretores a contratarem designers franceses sem consultar a Carl, que então se demitiu do cargo de gerente de designs. Apesar disso, Carl se manteve no conselho administrativo, mas junto a sua família fundou a Benz Söhne, uma empresa privada que produzia carros de boa qualidade que se popularizaram em Londres como táxis.</p>
          <p>As duas empresas, Benz & Cie e a Daimler Motoren Gesellschaft, em meio a uma crise econômica na Alemanha acabaram por se fundindo, e Carl Benz manteve se no conselho administrativo da empresa, que no ano de 1926 se tornou oficialmente a Mercedes-Benz. Sua carreira de empresário e inventor acabou no dia de sua morte, 4 de abril de 1929.</p>
        </ContentInfo>
        <ContentInfo>
          <h1>Breve História de Daimler Motoren Gesellschaft</h1>
          <p>	A Daimler Motoren Gesellschaft foi fundada em 1890, 8 anos após seus fundadores saírem da Deutz AG, tendo como seu propósito construir pequenos motores de alta velocidade baseados na tecnologia de motor estacionário. Também chamada de DMG, a empresa foi fundada pelo engenheiro e designer industrial Gottlieb Daimler e pelo designer de motores Wilhelm Maybach, esses que inovaram em seus automóveis ao inventar o motor de quatro tempos à gasolina, o carburador e outras invenções. Eles criavam motores pequenos de combustão interna para serem usados em terra, mar ou ar.</p>
          <p>Em 1894, Gottlieb Daimler, seu filho Paul e Wilhelm Maybach desenvolveram o motor Phoenix, notável por seu design inovador com quatro cilindros verticais e paralelos, válvulas de escape operadas por comando, um carburador com bico pulverizador patenteado por Maybach em 1893 e melhorias no sistema de transmissão por correia. Esse motor se tornou o principal produto da Daimler-Motoren-Gesellschaft e foi usado em carros, caminhões e barcos até a introdução do carro Mercedes em 1902.</p>
          <p>	A empresa não começou sendo um completo sucesso, visto que devido aos baixos lucros e a problemas financeiros de Daimler, este realizou um acordo com os industrialistas Max Von Duttenhofer e Wilhelm Lorenz juntos ao banqueiro Kilian Von Steiner, que possuía um banco de investimentos. O acordo definiu que a empresa deixaria de ser privada e tornaria-se de capital aberto, o que futuramente levou a desentendimentos por parte dos fundadores.</p>
          <p>Em 1890, Frederick Simms, um amigo e engenheiro de Daimler que havia recentemente chegado à Inglaterra, conseguiu direitos de patente para produzir os motores e automóveis de Daimler no Império Britânico. O negócio era promissor, o que levou o promotor de vendas inglês, chamado Lawson, a tentar comprar os direitos de produção da empresa de Simms. No final, foi feito um contrato de reassociação de Daimler e Maybach a DMG e junto a isso Lawson conseguiu os direitos de produção sendo o diretor de sua empresa o Daimler. A licença de produção dos produtos de Daimler, também foram requisitadas em outros lugares, como nos Estados Unidos da América com William Steinway e na França com Armand Peugeot, além da subsidiária da DMG no Império Austro-Húngaro.</p>
          <p>	No ano de 1896, Daimler e Maybach voltaram às boas relações com os financiadores da empresa, alcançando respectivamente os cargos de inspetor geral e diretor técnico, e o amigo de Daimler que ajudou a estabilizar as relações, Frederick Simms, tornou-se diretor da empresa. Porém, infelizmente Gottlieb Daimler morreu no ano de 1900, e somente depois de sua morte, ocorreu o sucesso dos modelos Mercedes, feitos por Maybach baseando-se em carros de corrida.</p>
          <p> Em 1902, Maybach criou um automóvel que viria a ser chamado de Mercedes 35 hp a pedido do comerciante austríaco Emil Jellinek, que estava fascinado pelo motor Phoenix e pelos carros de corrida. O nome Mercedes derivou de um motor que Maybach construiu para Jellinek em 1900, com 35 hp. Jellinek exigiu que o motor fosse chamado Daimler-Mercedes e, após o sucesso, pediu um novo modelo de veículos para comercializar e usar pessoalmente. Esse modelo ficou conhecido como Mercedes 35 hp. O carro só foi comercializado pela DMG quando seu sucesso foi considerado significativo.</p>
          <p>Misturando os refinamentos técnicos do novo motor de 4 cilindros de Maybach com um novo chassi, o automóvel impressionou o mundo dos esportes motorizados em 1901. Jellinek prometeu comprar um grande número dos carros de corrida se pudesse ser o único concessionário na Áustria-Hungria, França, Bélgica e EUA, usando o nome Daimler-Mercedes para o motor, e também se tornar membro do Conselho de Administração.</p>
          <p>A DMG, no ano de 1902, conseguiu expandir-se para Berlin, onde ela passou a produzir motores para veículos marinhos, lanchas, além de futuramente produzir caminhões comuns e caminhões de bombeiro. Tal expansão é a prova da versatilidade da empresa, que passou a estar presente na bolsa de valores de Stuttgart no ano de 1911, devido a sua expansão e aumento de produtividade. Ainda em 1902, após a DMG perceber que já havia concedido sua marca Daimler à Panhard & Levassor para toda a França, decidiu nomear todos os seus carros de Mercedes, em homenagem ao motor, e começou a produzir a série Mercedes. A grande demanda pelo carro rapidamente fez com que a DMG operasse a plena capacidade.</p>
          <p>Após a Primeira Guerra Mundial, a indústria automobilística na Alemanha enfrentou uma estagnação devido à baixa demanda e à taxação dos automóveis como itens de luxo pelo governo. Além disso, o país sofreu com uma escassez de petróleo.</p>
          <p>Em 1923, a produção da DMG caiu para 1020 unidades, enquanto a Benz & Cie. fabricava 1382 em Mannheim. O custo médio de um carro era de 25 milhões de marcos alemães. A DMG foi severamente impactada por greves e inflação, chegando ao limite. Para se manter, a empresa diversificou sua produção para bicicletas e máquinas de escrever Mercedes e até lançou sua própria moeda de emergência.</p>
          <p>Na década de 1870, enquanto trabalhava para Otto na Deutz AG Gasmotorenfabrik em Colônia, Daimler enviou um cartão-postal para sua esposa Emma Kunz, marcando sua residência com uma estrela de três pontas e escrevendo: "um dia esta estrela brilhará sobre nossas fábricas triunfantes". Essa frase inspirou Daimler e Maybach no desenvolvimento de motores leves e potentes para "terra, água e ar". Em 1900, após a morte de Daimler e o sucesso do Mercedes, seus filhos decidiram utilizar esse símbolo, tendo se tornado oficial em 1910 e posteriormente sendo adicionado um círculo em volta das estrelas.</p>
          <p>A crise econômica alemã, levou a Daimler Motoren Gesellschaft a realizar um acordo com a Benz & Cie, que posteriormente levou a padronização dos produtos das duas empresas. O mesmo acordo, foi o ponto de partida para a fusão das empresas, surgindo assim a Mercedes-Benz. O nome da nova empresa, homenageia o veículo de maior sucesso da DMG, o Mercedes, junto ao fundador da Benz & Cie, Karl Benz.</p>
        </ContentInfo>
        <ContentInfo>
          <img src={img} />
        </ContentInfo>
      </Content>
      <Footer/>
    </Container>
  )
}